name: Deploy to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: roadpeak/discoun3-merchants:latest
        no-cache: true
        build-args: |
          VITE_API_BASE_URL=https://api.discoun3ree.com/api/v1
          VITE_API_KEY=API_KEY_12345ABCDEF!@#67890-xyZQvTPOl
